[package]
name = "ukko-svg"
version = "0.1.0"
edition = "2021"

[dependencies]

xmltree = "0.11"
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = ["formatting", "local-offset", "serde"] }
